### ISSUE TITLE
Title Menu Ending

### ISSUE THREAD

**Issue by JaredBronstein** [JaredBronstein/Frozen_Harvest#5]
Title menu seems uninteractable when accessed after beating the game. Menu will display and scene changes but mouse cannot be moved nor are buttons able to be clicked

**Comment by dantogno** [comment]
@JaredBronstein what branch, how do I test quickly?

**Comment by JaredBronstein** [comment]
Milestone 5, and just click the red button

**Comment by dantogno** [comment]
@JaredBronstein Actually, I still don't know what to do. What scene? Do I need to beat the whole game? If so, you're gonna have to explain how. But really you should make a faster test case. We don't have time to play the whole game each time we need to test a fix.

**Comment by JaredBronstein** [comment]
You need to play the Farm scene and I positioned the player right next to the "end the game" red button and disabled the requirements to do so. Nevermind though, I think I've got a solution already figured out. Thanks for the help.
